/**
 * Emits `src/app/tokens.css` from `@tradetoken/design-tokens`.
 *
 * The handoff asks web to derive its CSS variables from the shared raw values
 * rather than restating them. Tailwind needs its theme statically at build
 * time, so the values are generated into a committed file instead of read at
 * runtime: regenerating produces a diff if the two ever drift, which a
 * hand-copied palette would not.
 *
 * Run with `bun run tokens`.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { fill, ink, palette, radius, ramps, space, stroke } from '@tradetoken/design-tokens';

const lines: string[] = [
  '/*',
  ' * GENERATED by scripts/generate-tokens-css.ts — do not edit by hand.',
  ' * Source of truth: packages/design-tokens. Run `bun run tokens` to refresh.',
  ' */',
  '',
  '@theme {',
];

const push = (name: string, value: string | number) =>
  lines.push(`  --${name}: ${typeof value === 'number' ? `${value}px` : value};`);

lines.push('  /* Surfaces and accents. */');
for (const [key, value] of Object.entries(palette)) push(`color-${kebab(key)}`, value);

lines.push('', '  /* Type colour scale — hierarchy is alpha on one ink. */');
for (const [key, value] of Object.entries(ink)) push(`color-ink-${kebab(key)}`, value);

lines.push('', '  /* Hairlines and translucent fills. */');
for (const [key, value] of Object.entries(stroke)) push(`color-stroke-${kebab(key)}`, value);
for (const [key, value] of Object.entries(fill)) push(`color-fill-${kebab(key)}`, value);

lines.push('', '  /* Ambient field ramps, dark -> light. */');
for (const [name, ramp] of Object.entries(ramps)) {
  ramp.forEach((stop, i) => push(`color-ramp-${kebab(name)}-${i + 1}`, stop));
}

lines.push('', '  /* Radii. */');
for (const [key, value] of Object.entries(radius)) push(`radius-${kebab(key)}`, value);

lines.push('', '  /* Spacing scale. */');
for (const [key, value] of Object.entries(space)) push(`spacing-${kebab(key)}`, value);

lines.push('}', '');

writeFileSync(fileURLToPath(new URL('../src/app/tokens.css', import.meta.url)), lines.join('\n'));

function kebab(value: string) {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
